### ISSUE TITLE
The 'cancel.png' image location failed.

### ISSUE THREAD

**Issue by psampont** [andreimaneasa/ColorPlugin#2]
With the 16812 version of JOSM under Linux, the plugin doesn't work anymore. There is a problem with the new icons in svg format instead of png format.

Here is the stacktrace :

org.openstreetmap.josm.tools.JosmRuntimeException: Fatal error: the 'cancel.png' image location failed. This is a major configuration issue. JOSM will be stopped.
	at org.openstreetmap.josm.tools.ImageProvider.getResource(ImageProvider.java:706)
	at org.openstreetmap.josm.tools.ImageProvider.get(ImageProvider.java:666)
	at org.openstreetmap.josm.tools.ImageProvider.get(ImageProvider.java:812)
	at org.openstreetmap.josm.gui.ExtendedDialog.setButtonIcons(ExtendedDialog.java:187)
	at andrei.josm.plugin.color.ColorDialog.<init>(ColorDialog.java:88)
	at andrei.josm.plugin.color.ColorAction.actionPerformed(ColorAction.java:36)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)

**Comment by simon04** [comment]
Ticket in JOSM bug tracker: https://josm.openstreetmap.de/ticket/20787
